# Generated by Django 4.0.4 on 2022-05-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urlString',
            new_name='url_string',
        ),
        migrations.AddField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
